# Generated by Django 5.1.6 on 2026-05-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafficLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "junction_id",
                    models.IntegerField(
                        choices=[
                            (1, "Junction Alpha (J1)"),
                            (2, "Junction Bravo (J2)"),
                            (3, "Junction Charlie (J3)"),
                            (4, "Junction Delta (J4)"),
                        ]
                    ),
                ),
                ("hour", models.IntegerField()),
                ("is_weekend", models.BooleanField(default=False)),
                (
                    "weather",
                    models.IntegerField(
                        choices=[
                            (0, "Clear / Standard Visibility"),
                            (1, "Precipitation / Heavy Rain"),
                            (2, "Extreme Fog / Low Visibility"),
                        ]
                    ),
                ),
                ("vehicle_count", models.IntegerField()),
                ("prediction_output", models.CharField(max_length=100)),
                ("timer_strategy", models.CharField(max_length=100)),
            ],
        ),
    ]
